environments:
  - environment: no_requests
    uninstall: [requests]
    install: []
    test-tools: true
    dev-reqs: true
  - environment: no_aiohttp
    uninstall: [aiohttp]
    install: []
    test-tools: true
    dev-reqs: true