trigger: none

jobs:
  # - job: 'win2019docker'
  #   displayName: 'Windows Docker Run'
  #   pool:
  #     vmImage: 'windows-2019'
  #   steps:
  #     - task: UsePythonVersion@0
  #       displayName: 'Use Python $(PythonVersion)'
  #       inputs:
  #         versionSpec: $(PythonVersion)
  #     - template: /eng/common/testproxy/test-proxy-docker.yml
  #     - template : /eng/pipelines/templates/steps/check-availability.yml

  - job: 'win2019tool'
    displayName: 'Check Windows'
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python pypy3'
        inputs:
          versionSpec: pypy3

      - pwsh: |
          $commonCertName = "ASP.NET Core HTTPS development certificate"

          # local machine
          $personalCert = Import-PfxCertificate -FilePath "$(Build.SourcesDirectory)/eng/common/testproxy/dotnet-devcert.pfx" -CertStoreLocation Cert:\LocalMachine\My -Password (ConvertTo-SecureString "password" -AsPlainText -Force)
          (Get-ChildItem -Path Cert:\LocalMachine\My\$($personalCert.Thumbprint)).FriendlyName = $commonCertName
          # $rootCert = Import-PfxCertificate -FilePath "$(Build.SourcesDirectory)/eng/common/testproxy/dotnet-devcert.pfx" -CertStoreLocation Cert:\LocalMachine\Root\ -Password (ConvertTo-SecureString "password" -AsPlainText -Force)
          # (Get-ChildItem -Path Cert:\LocalMachine\Root\$($rootCert.Thumbprint)).FriendlyName = $commonCertName

          # # current user
          # $personalCert = Import-PfxCertificate -FilePath "$(Build.SourcesDirectory)/eng/common/testproxy/dotnet-devcert.pfx" -CertStoreLocation Cert:\CurrentUser\My -Password (ConvertTo-SecureString "password" -AsPlainText -Force)
          # (Get-ChildItem -Path Cert:\CurrentUser\My\$($personalCert.Thumbprint)).FriendlyName = $commonCertName
          # $rootCert = Import-PfxCertificate -FilePath "$(Build.SourcesDirectory)/eng/common/testproxy/dotnet-devcert.pfx" -CertStoreLocation Cert:\CurrentUser\Root\ -Password (ConvertTo-SecureString "password" -AsPlainText -Force)
          # (Get-ChildItem -Path Cert:\CurrentUser\Root\$($rootCert.Thumbprint)).FriendlyName = $commonCertName
        displayName: Trust dev cert manually

      - pwsh: |
          Write-Host $env:PATH
          Write-Host "-----"
          python --version
          python -c "import sys; print(sys.executable)"
        displayName: Dump Path and python versions

  # - job: 'linux2020docker'
  #   displayName: 'Linux Docker Run'
  #   pool:
  #     vmImage: 'ubuntu-20.04'
  #   steps:
  #     - task: UsePythonVersion@0
  #       displayName: 'Use Python $(PythonVersion)'
  #       inputs:
  #         versionSpec: $(PythonVersion)
  #     - template: /eng/common/testproxy/test-proxy-docker.yml
  #     - template : /eng/pipelines/templates/steps/check-availability.yml

  - job: 'linux2020tool'
    displayName: 'Check Linux'
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python pypy7.3.7'
        inputs:
          versionSpec: pypy7.3.7

      - pwsh: |


          Write-Host $env:PATH
          Write-Host "-----"
          python --version
          python -c "import sys; print(sys.executable)"
        displayName: Dump Path and python versions

  - job: 'macos'
    displayName: 'Check Mac'
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python pypy3.8.12'
        inputs:
          versionSpec: pypy3.8.12

      - pwsh: |
          Write-Host $env:PATH
          Write-Host "-----"
          python --version
          python -c "import sys; print(sys.executable)"
        displayName: Dump Path and python versions
      # - pwsh: |
      #     security add-trusted-cert -h
      #   displayName: "Debug"
      # - pwsh: |
      #     sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $(Build.SourcesDirectory)/eng/common/testproxy/dotnet-devcert.pfx
      #   displayName: "Trust certificate attempt 2"
      # - template: /eng/common/testproxy/test-proxy-docker.yml
      # - template : /eng/pipelines/templates/steps/check-availability.yml