# Variables: 
#  'build_targeting_string' comma separated glob strings selecting the packages that should be built. EG: "azure-keyvault,azure-mgmt-batch" or "azure-*"

jobs:
- job: Live Test Linux 2.7
  dependsOn:
  - 'Build_Target_Packages'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: live.teststeps.template.yml
    parameters:
      pythonVersion: '2.7'

- job: Live Test Windows 3.7
  dependsOn:
  - 'Build_Target_Packages'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: live.teststeps.template.yml
    parameters:
      pythonVersion: '3.7'

- job: Live Test OSX 3.6
  dependsOn:
  - 'Build_Target_Packages'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: live.teststeps.template.yml
    parameters:
      pythonVersion: '3.6'