# Variables: 
#  'build_targeting_string' comma separated glob strings selecting the packages that should be built. EG: "azure-keyvault,azure-mgmt-batch" or "azure-*"

jobs:
- job: 'Live_Test_Linux_2.7'
  dependsOn:
  - 'Build_Target_Packages'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: live.teststeps.template.yml
    parameters:
      pythonVersion: '2.7'

- job: 'Live_Test_Windows_3.7'
  dependsOn:
  - 'Build_Target_Packages'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: live.teststeps.template.yml
    parameters:
      pythonVersion: '3.7'

- job: 'Live_Test_OSX_3.6'
  dependsOn:
  - 'Build_Target_Packages'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: live.teststeps.template.yml
    parameters:
      pythonVersion: '3.6'